providers:
  - name: aws
    namespace: hashicorp
    min_version: 5.0.6
  - name: sbercloud
    namespace: sbercloud-terraform
#  - name: google
#    namespace: hashicorp
#  - name: azure
#    namespace: hashicorp